-- ===============================
-- Load HospitalDB synthetic dataset
-- Generated by code/generate_synthetic_data.py
--
-- Run from the project root with LOCAL INFILE enabled, for example:
-- mysql --local-infile=1 -u root -p < sql/load.sql
-- ===============================

USE HospitalDB;
SET NAMES utf8mb4;

-- ===============================
-- Reference data
-- ===============================

LOAD DATA LOCAL INFILE 'data/diagnosis.csv'
INTO TABLE Diagnosis
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(ICDCode, `Description`);

LOAD DATA LOCAL INFILE 'data/cost.csv'
INTO TABLE Cost
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(KENCode, `Description`, BaseCost, PredictedAvgTime);

LOAD DATA LOCAL INFILE 'data/procedure_type.csv'
INTO TABLE ProcedureType
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(ProcCode, ProcName, ProcType, ProcDuration, ProcCost);

LOAD DATA LOCAL INFILE 'data/lab_test.csv'
INTO TABLE LabTest
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(LabCode, LabType, LabDescription, LabCost, IsActive);

LOAD DATA LOCAL INFILE 'data/drug_type.csv'
INTO TABLE DrugType
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(DrugID, `Name`, `Route`, AuthCountry, AuthHolder, MasterFileLocation, Email);

LOAD DATA LOCAL INFILE 'data/substances.csv'
INTO TABLE Substances
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(ID, `Name`);

LOAD DATA LOCAL INFILE 'data/has_substances.csv'
INTO TABLE HasSubstances
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(SubID, DrugID);

LOAD DATA LOCAL INFILE 'data/drug_support_phone.csv'
INTO TABLE DrugSupportPhone
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(DrugID, Phone);

LOAD DATA LOCAL INFILE 'data/insurance_provider.csv'
INTO TABLE InsuranceProvider
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(`Name`);

LOAD DATA LOCAL INFILE 'data/shift_type.csv'
INTO TABLE ShiftType
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(`Name`, StartTime);

-- ===============================
-- Staff and organization
-- ===============================

LOAD DATA LOCAL INFILE 'data/staff.csv'
INTO TABLE Staff
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(AMKA, FirstName, LastName, BirthDate, Email, HireDate, IsActive, `Type`);

LOAD DATA LOCAL INFILE 'data/staff_phone.csv'
INTO TABLE StaffPhone
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(StaffAMKA, Phone);

LOAD DATA LOCAL INFILE 'data/doctor.csv'
INTO TABLE Doctor
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(AMKA, License, Specialty, `Rank`, @SupervisorAMKA)
SET SupervisorAMKA = NULLIF(@SupervisorAMKA, '');

LOAD DATA LOCAL INFILE 'data/department.csv'
INTO TABLE Department
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(DepartmentID, `Name`, `Description`, Floor, Building, DirectorAMKA);

LOAD DATA LOCAL INFILE 'data/doctor_department.csv'
INTO TABLE DoctorDepartment
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(DoctorAMKA, DepartmentID);

LOAD DATA LOCAL INFILE 'data/nurse.csv'
INTO TABLE Nurse
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(AMKA, `Rank`, DepartmentID);

LOAD DATA LOCAL INFILE 'data/admin_staff.csv'
INTO TABLE AdminStaff
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(AMKA, `Role`, Office, DepartmentID);

LOAD DATA LOCAL INFILE 'data/room.csv'
INTO TABLE Room
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(ID, DepartmentID, `Type`, `State`);

-- ===============================
-- Patients
-- ===============================

LOAD DATA LOCAL INFILE 'data/patient.csv'
INTO TABLE Patient
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(AMKA, FirstName, LastName, FatherName, BirthDate, Gender, `Weight`, `Height`, `Address`, Email, Profession, Nationality, isActive, InsuranceProviderName);

LOAD DATA LOCAL INFILE 'data/patient_phone.csv'
INTO TABLE PatientPhone
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(PatientAMKA, Phone);

LOAD DATA LOCAL INFILE 'data/emergency_contact.csv'
INTO TABLE EmergencyContact
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(`ID`, PatientAMKA, FirstName, LastName, `Address`, Email, Relation);

LOAD DATA LOCAL INFILE 'data/em_contact_phone.csv'
INTO TABLE EmContactPhone
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(`ID`, Phone);

-- ===============================
-- Shifts
-- ===============================

LOAD DATA LOCAL INFILE 'data/shift.csv'
INTO TABLE Shift
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(DepartmentID, ShiftTypeName, `Date`);

LOAD DATA LOCAL INFILE 'data/has_doctor.csv'
INTO TABLE hasDoctor
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(DepartmentID, ShiftTypeName, ShiftDate, DoctorAMKA);

LOAD DATA LOCAL INFILE 'data/has_nurse.csv'
INTO TABLE hasNurse
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(DepartmentID, ShiftTypeName, ShiftDate, NurseAMKA);

LOAD DATA LOCAL INFILE 'data/has_admin.csv'
INTO TABLE hasAdmin
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(DepartmentID, ShiftTypeName, ShiftDate, AdminAMKA);

-- ===============================
-- Clinical events
-- ===============================

LOAD DATA LOCAL INFILE 'data/hospitalization.csv'
INTO TABLE Hospitalization
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(HospitalizationID, AdmissionDateTime, PatientAMKA, ExitDateTime, RoomID, DepartmentID, KENcode);

LOAD DATA LOCAL INFILE 'data/admission_diagnosis.csv'
INTO TABLE AdmissionDiagnosis
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(HospitalizationID, ICDCode);

LOAD DATA LOCAL INFILE 'data/exit_diagnosis.csv'
INTO TABLE ExitDiagnosis
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(HospitalizationID, ICDCode);

LOAD DATA LOCAL INFILE 'data/triage_event.csv'
INTO TABLE TriageEvent
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(TriageID, Symptoms, EmergencyLevel, Outcome, TriageDateTime, @HospitalizationID, PatientAMKA, @AssessmentDateTime, NurseAMKA)
SET HospitalizationID = NULLIF(@HospitalizationID, ''), AssessmentDateTime = NULLIF(@AssessmentDateTime, '');

LOAD DATA LOCAL INFILE 'data/hosp_evaluation.csv'
INTO TABLE HospEvaluation
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(HospitalizationID, QoNurseS, Cleanliness, Food, GeneralExperience);

LOAD DATA LOCAL INFILE 'data/hosp_lab_test.csv'
INTO TABLE HospLabTest
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(Id, HospitalizationID, LabCode, LabDateTime, LabResult, PendingResult, DoctorAMKA);

-- ===============================
-- Procedures
-- ===============================

LOAD DATA LOCAL INFILE 'data/procedure_room.csv'
INTO TABLE ProcedureRoom
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(ProcRoomID, ProcRoomType, `State`);

LOAD DATA LOCAL INFILE 'data/procedure_event.csv'
INTO TABLE ProcedureEvent
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(ProcEventID, ProcRoomID, `DateTime`, MainDocAMKA, ProcedureCode, HospitalizationID);

LOAD DATA LOCAL INFILE 'data/operates_in.csv'
INTO TABLE operates_in
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(DoctorAMKA, ProcEventID);

LOAD DATA LOCAL INFILE 'data/assists_in.csv'
INTO TABLE assists_in
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(NurseAMKA, ProcEventID);

LOAD DATA LOCAL INFILE 'data/helps_in.csv'
INTO TABLE helps_in
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(AdminStaffAMKA, ProcEventID);

-- ===============================
-- Allergies and prescriptions
-- ===============================

LOAD DATA LOCAL INFILE 'data/allergic_to.csv'
INTO TABLE allergic_to
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(PatientAMKA, SubstanceID);

LOAD DATA LOCAL INFILE 'data/prescription_event.csv'
INTO TABLE PrescriptionEvent
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(PrescriptionID, HospitalizationID, DoctorAMKA, DrugID, Dosage, frequency, PrescriptionDate, StartDate, @EndDate)
SET EndDate = NULLIF(@EndDate, '');

DROP TEMPORARY TABLE IF EXISTS DoctorEvaluationLoad;
CREATE TEMPORARY TABLE DoctorEvaluationLoad (
    HospitalizationID INT NOT NULL,
    DoctorAMKA CHAR(11) NOT NULL,
    QoDoctorS TINYINT NOT NULL,
    PRIMARY KEY (HospitalizationID, DoctorAMKA)
);

LOAD DATA LOCAL INFILE 'data/doctor_evaluation.csv'
INTO TABLE DoctorEvaluationLoad
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(HospitalizationID, DoctorAMKA, QoDoctorS);

INSERT INTO DoctorEvaluation (HospitalizationID, DoctorAMKA, QoDoctorS)
SELECT del.HospitalizationID, del.DoctorAMKA, del.QoDoctorS
FROM DoctorEvaluationLoad del
WHERE EXISTS (
    SELECT 1
    FROM PrescriptionEvent pe
    WHERE pe.HospitalizationID = del.HospitalizationID
      AND pe.DoctorAMKA = del.DoctorAMKA
);

-- ===============================
-- Images
-- ===============================

LOAD DATA LOCAL INFILE 'data/image.csv'
INTO TABLE `Image`
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(ImageID, ImageURL, ImageDescription, @ProcRoomId, @StaffAMKA, @DepartmentID, @RoomID, @RoomDepartmentID)
SET
    ProcRoomId = NULLIF(@ProcRoomId, ''),
    StaffAMKA = NULLIF(@StaffAMKA, ''),
    DepartmentID = NULLIF(@DepartmentID, ''),
    RoomID = NULLIF(@RoomID, ''),
    RoomDepartmentID = NULLIF(@RoomDepartmentID, '');